Diplom part1
SharkoYaroslavQA19/FinalSurge_Sharko pull request #2
Opened 2022-09-05 21:31 UTC by SharkoYaroslavQA19

2022-09-06 11:18 UTC, voropa requested changes

2022-09-06 11:18 UTC, voropa commented on src/test/java/Utils/DateFactory.java
> +public class DateFactory {
Лучше переименуйте этот класс в TestDataFactory.
Date - дата (год месяц т.д)
Data - данные, информация

2022-09-06 11:18 UTC, voropa commented on src/test/java/tests/BikesTest.java
> +    protected BikesPage BikesPage;
Названия переменных и полей в java должны быть с маленькой буквы

2022-09-06 11:18 UTC, voropa commented on src/test/java/tests/DailyVitalsTest.java
> +        Assert.assertTrue(HomePage.isUserIconDisplayed());
В before/after методах не должно быть assert'ов. Проверки должны быть в тестах

2022-09-14 18:25 UTC, voropa requested changes

2022-09-14 18:25 UTC, voropa commented on src/test/java/tests/WorkoutCalculatorsTest.java
> +    @Test(groups = {"regression"},description = "using a calculator to calculate intensive running")
По идее эти два теста выполняют одни и те же действия, просто с разными данными, значит их можно сделать data-driven

2022-09-15 07:02 UTC, SharkoYaroslavQA19 commented on src/test/java/tests/WorkoutCalculatorsTest.java
> +    @Test(groups = {"regression"},description = "using a calculator to calculate intensive running")
Не совсем понял ваше замечание. Данные заполняются на разных формах.

2022-09-15 08:30 UTC, voropa approved these changes

2022-09-15 08:30 UTC, voropa commented on src/test/java/tests/WorkoutCalculatorsTest.java
> +    @Test(groups = {"regression"},description = "using a calculator to calculate intensive running")
Точно, не заметил. Тогда все верно

2022-09-15 09:28 UTC, merged